const freeDays = {
  janeiro: [
    { day: 1, status: 'available' },
    { day: 2, status: 'available' },
    { day: 3, status: 'unavailable' },
    { day: 4, status: 'available' },
    { day: 5, status: 'available' },
    { day: 6, status: 'unavailable' },
    { day: 7, status: 'unavailable' },
    { day: 8, status: 'available' },
    { day: 9, status: 'unavailable' },
    { day: 10, status: 'available' },
    { day: 11, status: 'available' },
    { day: 12, status: 'available' },
    { day: 13, status: 'unavailable' },
    { day: 14, status: 'unavailable' },
    { day: 15, status: 'available' },
    { day: 16, status: 'unavailable' },
    { day: 17, status: 'available' },
    { day: 18, status: 'unavailable' },
    { day: 19, status: 'available' },
    { day: 20, status: 'unavailable' },
    { day: 21, status: 'unavailable' },
    { day: 22, status: 'available' },
    { day: 23, status: 'available' },
    { day: 24, status: 'unavailable' },
    { day: 25, status: 'available' },
    { day: 26, status: 'unavailable' },
    { day: 27, status: 'unavailable' },
    { day: 28, status: 'unavailable' },
    { day: 29, status: 'unavailable' },
    { day: 30, status: 'available' },
  ],
  fevereiro: [
    { day: 1, status: 'available' },
    { day: 2, status: 'available' },
    { day: 3, status: 'available' },
    { day: 4, status: 'unavailable' },
    { day: 5, status: 'available' },
    { day: 6, status: 'unavailable' },
    { day: 7, status: 'unavailable' },
    { day: 8, status: 'available' },
    { day: 9, status: 'available' },
    { day: 10, status: 'unavailable' },
    { day: 11, status: 'available' },
    { day: 12, status: 'available' },
    { day: 13, status: 'unavailable' },
    { day: 14, status: 'unavailable' },
    { day: 15, status: 'available' },
    { day: 16, status: 'available' },
    { day: 17, status: 'available' },
    { day: 18, status: 'available' },
    { day: 19, status: 'available' },
    { day: 20, status: 'unavailable' },
    { day: 21, status: 'unavailable' },
    { day: 22, status: 'available' },
    { day: 23, status: 'available' },
    { day: 24, status: 'available' },
    { day: 25, status: 'unavailable' },
    { day: 26, status: 'available' },
    { day: 27, status: 'unavailable' },
    { day: 28, status: 'unavailable' },
    { day: 29, status: 'unavailable' },
    { day: 30, status: 'available' },
  ],
  marco: [
    { day: 1, status: 'available' },
    { day: 2, status: 'available' },
    { day: 3, status: 'available' },
    { day: 4, status: 'available' },
    { day: 5, status: 'available' },
    { day: 6, status: 'unavailable' },
    { day: 7, status: 'unavailable' },
    { day: 8, status: 'available' },
    { day: 9, status: 'available' },
    { day: 10, status: 'available' },
    { day: 11, status: 'available' },
    { day: 12, status: 'available' },
    { day: 13, status: 'unavailable' },
    { day: 14, status: 'unavailable' },
    { day: 15, status: 'available' },
    { day: 16, status: 'unavailable' },
    { day: 17, status: 'available' },
    { day: 18, status: 'unavailable' },
    { day: 19, status: 'available' },
    { day: 20, status: 'unavailable' },
    { day: 21, status: 'unavailable' },
    { day: 22, status: 'available' },
    { day: 23, status: 'available' },
    { day: 24, status: 'available' },
    { day: 25, status: 'unavailable' },
    { day: 26, status: 'available' },
    { day: 27, status: 'unavailable' },
    { day: 28, status: 'unavailable' },
    { day: 29, status: 'available' },
    { day: 30, status: 'available' },
  ],
  abril: [
    { day: 1, status: 'available' },
    { day: 2, status: 'available' },
    { day: 3, status: 'available' },
    { day: 4, status: 'available' },
    { day: 5, status: 'available' },
    { day: 6, status: 'unavailable' },
    { day: 7, status: 'unavailable' },
    { day: 8, status: 'available' },
    { day: 9, status: 'available' },
    { day: 10, status: 'available' },
    { day: 11, status: 'available' },
    { day: 12, status: 'available' },
    { day: 13, status: 'unavailable' },
    { day: 14, status: 'unavailable' },
    { day: 15, status: 'available' },
    { day: 16, status: 'available' },
    { day: 17, status: 'available' },
    { day: 18, status: 'unavailable' },
    { day: 19, status: 'available' },
    { day: 20, status: 'unavailable' },
    { day: 21, status: 'unavailable' },
    { day: 22, status: 'available' },
    { day: 23, status: 'unavailable' },
    { day: 24, status: 'available' },
    { day: 25, status: 'unavailable' },
    { day: 26, status: 'available' },
    { day: 27, status: 'unavailable' },
    { day: 28, status: 'unavailable' },
    { day: 29, status: 'available' },
    { day: 30, status: 'available' },
  ],
  maio: [
    { day: 1, status: 'available' },
    { day: 2, status: 'available' },
    { day: 3, status: 'available' },
    { day: 4, status: 'unavailable' },
    { day: 5, status: 'available' },
    { day: 6, status: 'unavailable' },
    { day: 7, status: 'unavailable' },
    { day: 8, status: 'available' },
    { day: 9, status: 'available' },
    { day: 10, status: 'unavailable' },
    { day: 11, status: 'available' },
    { day: 12, status: 'available' },
    { day: 13, status: 'unavailable' },
    { day: 14, status: 'unavailable' },
    { day: 15, status: 'available' },
    { day: 16, status: 'available' },
    { day: 17, status: 'unavailable' },
    { day: 18, status: 'unavailable' },
    { day: 19, status: 'available' },
    { day: 20, status: 'unavailable' },
    { day: 21, status: 'unavailable' },
    { day: 22, status: 'available' },
    { day: 23, status: 'available' },
    { day: 24, status: 'unavailable' },
    { day: 25, status: 'available' },
    { day: 26, status: 'available' },
    { day: 27, status: 'unavailable' },
    { day: 28, status: 'unavailable' },
    { day: 29, status: 'available' },
    { day: 30, status: 'available' },
  ],
  junho: [
    { day: 1, status: 'available' },
    { day: 2, status: 'available' },
    { day: 3, status: 'available' },
    { day: 4, status: 'unavailable' },
    { day: 5, status: 'available' },
    { day: 6, status: 'unavailable' },
    { day: 7, status: 'unavailable' },
    { day: 8, status: 'available' },
    { day: 9, status: 'unavailable' },
    { day: 10, status: 'available' },
    { day: 11, status: 'available' },
    { day: 12, status: 'available' },
    { day: 13, status: 'unavailable' },
    { day: 14, status: 'unavailable' },
    { day: 15, status: 'available' },
    { day: 16, status: 'available' },
    { day: 17, status: 'unavailable' },
    { day: 18, status: 'available' },
    { day: 19, status: 'available' },
    { day: 20, status: 'unavailable' },
    { day: 21, status: 'unavailable' },
    { day: 22, status: 'available' },
    { day: 23, status: 'unavailable' },
    { day: 24, status: 'unavailable' },
    { day: 25, status: 'unavailable' },
    { day: 26, status: 'available' },
    { day: 27, status: 'unavailable' },
    { day: 28, status: 'unavailable' },
    { day: 29, status: 'unavailable' },
    { day: 30, status: 'unavailable' },
  ],
  julho: [
    { day: 1, status: 'available' },
    { day: 2, status: 'unavailable' },
    { day: 3, status: 'available' },
    { day: 4, status: 'unavailable' },
    { day: 5, status: 'available' },
    { day: 6, status: 'unavailable' },
    { day: 7, status: 'unavailable' },
    { day: 8, status: 'available' },
    { day: 9, status: 'available' },
    { day: 10, status: 'unavailable' },
    { day: 11, status: 'available' },
    { day: 12, status: 'available' },
    { day: 13, status: 'unavailable' },
    { day: 14, status: 'unavailable' },
    { day: 15, status: 'available' },
    { day: 16, status: 'available' },
    { day: 17, status: 'available' },
    { day: 18, status: 'unavailable' },
    { day: 19, status: 'available' },
    { day: 20, status: 'unavailable' },
    { day: 21, status: 'unavailable' },
    { day: 22, status: 'available' },
    { day: 23, status: 'available' },
    { day: 24, status: 'unavailable' },
    { day: 25, status: 'available' },
    { day: 26, status: 'available' },
    { day: 27, status: 'unavailable' },
    { day: 28, status: 'unavailable' },
    { day: 29, status: 'unavailable' },
    { day: 30, status: 'available' },
  ],
  agosto: [
    { day: 1, status: 'available' },
    { day: 2, status: 'available' },
    { day: 3, status: 'available' },
    { day: 4, status: 'unavailable' },
    { day: 5, status: 'available' },
    { day: 6, status: 'unavailable' },
    { day: 7, status: 'unavailable' },
    { day: 8, status: 'available' },
    { day: 9, status: 'available' },
    { day: 10, status: 'available' },
    { day: 11, status: 'available' },
    { day: 12, status: 'available' },
    { day: 13, status: 'unavailable' },
    { day: 14, status: 'unavailable' },
    { day: 15, status: 'available' },
    { day: 16, status: 'unavailable' },
    { day: 17, status: 'available' },
    { day: 18, status: 'available' },
    { day: 19, status: 'available' },
    { day: 20, status: 'unavailable' },
    { day: 21, status: 'unavailable' },
    { day: 22, status: 'available' },
    { day: 23, status: 'available' },
    { day: 24, status: 'unavailable' },
    { day: 25, status: 'available' },
    { day: 26, status: 'available' },
    { day: 27, status: 'unavailable' },
    { day: 28, status: 'unavailable' },
    { day: 29, status: 'available' },
    { day: 30, status: 'unavailable' },
  ],
  setembro: [
    { day: 1, status: 'available' },
    { day: 2, status: 'unavailable' },
    { day: 3, status: 'available' },
    { day: 4, status: 'unavailable' },
    { day: 5, status: 'available' },
    { day: 6, status: 'unavailable' },
    { day: 7, status: 'unavailable' },
    { day: 8, status: 'available' },
    { day: 9, status: 'available' },
    { day: 10, status: 'available' },
    { day: 11, status: 'available' },
    { day: 12, status: 'available' },
    { day: 13, status: 'unavailable' },
    { day: 14, status: 'unavailable' },
    { day: 15, status: 'available' },
    { day: 16, status: 'available' },
    { day: 17, status: 'unavailable' },
    { day: 18, status: 'available' },
    { day: 19, status: 'available' },
    { day: 20, status: 'unavailable' },
    { day: 21, status: 'unavailable' },
    { day: 22, status: 'available' },
    { day: 23, status: 'available' },
    { day: 24, status: 'available' },
    { day: 25, status: 'available' },
    { day: 26, status: 'available' },
    { day: 27, status: 'unavailable' },
    { day: 28, status: 'unavailable' },
    { day: 29, status: 'available' },
    { day: 30, status: 'unavailable' },
  ],
  outubro: [
    { day: 1, status: 'available' },
    { day: 2, status: 'available' },
    { day: 3, status: 'unavailable' },
    { day: 4, status: 'available' },
    { day: 5, status: 'available' },
    { day: 6, status: 'unavailable' },
    { day: 7, status: 'unavailable' },
    { day: 8, status: 'available' },
    { day: 9, status: 'available' },
    { day: 10, status: 'available' },
    { day: 11, status: 'unavailable' },
    { day: 12, status: 'available' },
    { day: 13, status: 'unavailable' },
    { day: 14, status: 'unavailable' },
    { day: 15, status: 'available' },
    { day: 16, status: 'available' },
    { day: 17, status: 'unavailable' },
    { day: 18, status: 'available' },
    { day: 19, status: 'available' },
    { day: 20, status: 'unavailable' },
    { day: 21, status: 'unavailable' },
    { day: 22, status: 'available' },
    { day: 23, status: 'available' },
    { day: 24, status: 'available' },
    { day: 25, status: 'unavailable' },
    { day: 26, status: 'available' },
    { day: 27, status: 'unavailable' },
    { day: 28, status: 'unavailable' },
    { day: 29, status: 'available' },
    { day: 30, status: 'available' },
  ],
  novembro: [
    { day: 1, status: 'available' },
    { day: 2, status: 'available' },
    { day: 3, status: 'unavailable' },
    { day: 4, status: 'unavailable' },
    { day: 5, status: 'available' },
    { day: 6, status: 'unavailable' },
    { day: 7, status: 'unavailable' },
    { day: 8, status: 'available' },
    { day: 9, status: 'available' },
    { day: 10, status: 'available' },
    { day: 11, status: 'unavailable' },
    { day: 12, status: 'unavailable' },
    { day: 13, status: 'unavailable' },
    { day: 14, status: 'unavailable' },
    { day: 15, status: 'available' },
    { day: 16, status: 'available' },
    { day: 17, status: 'available' },
    { day: 18, status: 'available' },
    { day: 19, status: 'available' },
    { day: 20, status: 'unavailable' },
    { day: 21, status: 'unavailable' },
    { day: 22, status: 'available' },
    { day: 23, status: 'unavailable' },
    { day: 24, status: 'available' },
    { day: 25, status: 'available' },
    { day: 26, status: 'available' },
    { day: 27, status: 'unavailable' },
    { day: 28, status: 'unavailable' },
    { day: 29, status: 'available' },
    { day: 30, status: 'available' },
  ],
  dezembro: [
    { day: 1, status: 'available' },
    { day: 2, status: 'available' },
    { day: 3, status: 'available' },
    { day: 4, status: 'unavailable' },
    { day: 5, status: 'available' },
    { day: 6, status: 'unavailable' },
    { day: 7, status: 'unavailable' },
    { day: 8, status: 'available' },
    { day: 9, status: 'available' },
    { day: 10, status: 'available' },
    { day: 11, status: 'available' },
    { day: 12, status: 'available' },
    { day: 13, status: 'unavailable' },
    { day: 14, status: 'unavailable' },
    { day: 15, status: 'available' },
    { day: 16, status: 'available' },
    { day: 17, status: 'available' },
    { day: 18, status: 'unavailable' },
    { day: 19, status: 'available' },
    { day: 20, status: 'unavailable' },
    { day: 21, status: 'unavailable' },
    { day: 22, status: 'available' },
    { day: 23, status: 'available' },
    { day: 24, status: 'unavailable' },
    { day: 25, status: 'available' },
    { day: 26, status: 'available' },
    { day: 27, status: 'unavailable' },
    { day: 28, status: 'unavailable' },
    { day: 29, status: 'available' },
    { day: 30, status: 'unavailable' },
  ],
};

const useFreeDays = (currentMonth = 'maio') => {
  // remove accents
  const month = currentMonth
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .trim();

  let actual = [];
  console.log(month);
  if (freeDays[month]) {
    actual = freeDays[month];
  }

  return [actual, freeDays];
};

export default useFreeDays;
