// const freeDays = {
//   janeiro: [
//     { day: 1, status: 'available', click: 0 },
//     { day: 2, status: 'available' },
//     { day: 3, status: 'available', click: 0 },
//     { day: 4, status: 'available', click: 0 },
//     { day: 5, status: 'available', click: 0 },
//     { day: 6, status: 'unavailable', click: 0 },
//     { day: 7, status: 'unavailable', click: 0 },
//     { day: 8, status: 'available', click: 0 },
//     { day: 9, status: 'available', click: 0 },
//     { day: 10, status: 'available', click: 0 },
//     { day: 11, status: 'available', click: 0 },
//     { day: 12, status: 'available', click: 0 },
//     { day: 13, status: 'unavailable', click: 0 },
//     { day: 14, status: 'unavailable', click: 0 },
//     { day: 15, status: 'available', click: 0 },
//     { day: 16, status: 'available', click: 0 },
//     { day: 17, status: 'available', click: 0 },
//     { day: 18, status: 'available', click: 0 },
//     { day: 19, status: 'available', click: 0 },
//     { day: 20, status: 'unavailable', click: 0 },
//     { day: 21, status: 'unavailable', click: 0 },
//     { day: 22, status: 'available', click: 0 },
//     { day: 23, status: 'available', click: 0 },
//     { day: 24, status: 'available', click: 0 },
//     { day: 25, status: 'available', click: 0 },
//     { day: 26, status: 'available', click: 0 },
//     { day: 27, status: 'unavailable', click: 0 },
//     { day: 28, status: 'unavailable', click: 0 },
//     { day: 29, status: 'available', click: 0 },
//     { day: 30, status: 'available', click: 0 },
//   ],
//   fevereiro: [
//     { day: 1, status: 'available', click: 0 },
//     { day: 2, status: 'available' },
//     { day: 3, status: 'available', click: 0 },
//     { day: 4, status: 'available', click: 0 },
//     { day: 5, status: 'available', click: 0 },
//     { day: 6, status: 'unavailable', click: 0 },
//     { day: 7, status: 'unavailable', click: 0 },
//     { day: 8, status: 'available', click: 0 },
//     { day: 9, status: 'available', click: 0 },
//     { day: 10, status: 'available', click: 0 },
//     { day: 11, status: 'available', click: 0 },
//     { day: 12, status: 'available', click: 0 },
//     { day: 13, status: 'unavailable', click: 0 },
//     { day: 14, status: 'unavailable', click: 0 },
//     { day: 15, status: 'available', click: 0 },
//     { day: 16, status: 'available', click: 0 },
//     { day: 17, status: 'available', click: 0 },
//     { day: 18, status: 'available', click: 0 },
//     { day: 19, status: 'available', click: 0 },
//     { day: 20, status: 'unavailable', click: 0 },
//     { day: 21, status: 'unavailable', click: 0 },
//     { day: 22, status: 'available', click: 0 },
//     { day: 23, status: 'available', click: 0 },
//     { day: 24, status: 'available', click: 0 },
//     { day: 25, status: 'available', click: 0 },
//     { day: 26, status: 'available', click: 0 },
//     { day: 27, status: 'unavailable', click: 0 },
//     { day: 28, status: 'unavailable', click: 0 },
//     { day: 29, status: 'available', click: 0 },
//     { day: 30, status: 'available', click: 0 },
//   ],
//   marco: [
//     { day: 1, status: 'available', click: 0 },
//     { day: 2, status: 'available' },
//     { day: 3, status: 'available', click: 0 },
//     { day: 4, status: 'available', click: 0 },
//     { day: 5, status: 'available', click: 0 },
//     { day: 6, status: 'unavailable', click: 0 },
//     { day: 7, status: 'unavailable', click: 0 },
//     { day: 8, status: 'available', click: 0 },
//     { day: 9, status: 'available', click: 0 },
//     { day: 10, status: 'available', click: 0 },
//     { day: 11, status: 'available', click: 0 },
//     { day: 12, status: 'available', click: 0 },
//     { day: 13, status: 'unavailable', click: 0 },
//     { day: 14, status: 'unavailable', click: 0 },
//     { day: 15, status: 'available', click: 0 },
//     { day: 16, status: 'available', click: 0 },
//     { day: 17, status: 'available', click: 0 },
//     { day: 18, status: 'available', click: 0 },
//     { day: 19, status: 'available', click: 0 },
//     { day: 20, status: 'unavailable', click: 0 },
//     { day: 21, status: 'unavailable', click: 0 },
//     { day: 22, status: 'available', click: 0 },
//     { day: 23, status: 'available', click: 0 },
//     { day: 24, status: 'available', click: 0 },
//     { day: 25, status: 'available', click: 0 },
//     { day: 26, status: 'available', click: 0 },
//     { day: 27, status: 'unavailable', click: 0 },
//     { day: 28, status: 'unavailable', click: 0 },
//     { day: 29, status: 'available', click: 0 },
//     { day: 30, status: 'available', click: 0 },
//   ],
//   abril: [
//     { day: 1, status: 'available', click: 0 },
//     { day: 2, status: 'available' },
//     { day: 3, status: 'available', click: 0 },
//     { day: 4, status: 'available', click: 0 },
//     { day: 5, status: 'available', click: 0 },
//     { day: 6, status: 'unavailable', click: 0 },
//     { day: 7, status: 'unavailable', click: 0 },
//     { day: 8, status: 'available', click: 0 },
//     { day: 9, status: 'available', click: 0 },
//     { day: 10, status: 'available', click: 0 },
//     { day: 11, status: 'available', click: 0 },
//     { day: 12, status: 'available', click: 0 },
//     { day: 13, status: 'unavailable', click: 0 },
//     { day: 14, status: 'unavailable', click: 0 },
//     { day: 15, status: 'available', click: 0 },
//     { day: 16, status: 'available', click: 0 },
//     { day: 17, status: 'available', click: 0 },
//     { day: 18, status: 'available', click: 0 },
//     { day: 19, status: 'available', click: 0 },
//     { day: 20, status: 'unavailable', click: 0 },
//     { day: 21, status: 'unavailable', click: 0 },
//     { day: 22, status: 'available', click: 0 },
//     { day: 23, status: 'available', click: 0 },
//     { day: 24, status: 'available', click: 0 },
//     { day: 25, status: 'available', click: 0 },
//     { day: 26, status: 'available', click: 0 },
//     { day: 27, status: 'unavailable', click: 0 },
//     { day: 28, status: 'unavailable', click: 0 },
//     { day: 29, status: 'available', click: 0 },
//     { day: 30, status: 'available', click: 0 },
//   ],
//   maio: [
//     { day: 1, status: 'available', click: 0 },
//     { day: 2, status: 'available' },
//     { day: 3, status: 'available', click: 0 },
//     { day: 4, status: 'available', click: 0 },
//     { day: 5, status: 'available', click: 0 },
//     { day: 6, status: 'unavailable', click: 0 },
//     { day: 7, status: 'unavailable', click: 0 },
//     { day: 8, status: 'available', click: 0 },
//     { day: 9, status: 'available', click: 0 },
//     { day: 10, status: 'available', click: 0 },
//     { day: 11, status: 'available', click: 0 },
//     { day: 12, status: 'available', click: 0 },
//     { day: 13, status: 'unavailable', click: 0 },
//     { day: 14, status: 'unavailable', click: 0 },
//     { day: 15, status: 'available', click: 0 },
//     { day: 16, status: 'available', click: 0 },
//     { day: 17, status: 'available', click: 0 },
//     { day: 18, status: 'available', click: 0 },
//     { day: 19, status: 'available', click: 0 },
//     { day: 20, status: 'unavailable', click: 0 },
//     { day: 21, status: 'unavailable', click: 0 },
//     { day: 22, status: 'available', click: 0 },
//     { day: 23, status: 'available', click: 0 },
//     { day: 24, status: 'available', click: 0 },
//     { day: 25, status: 'available', click: 0 },
//     { day: 26, status: 'available', click: 0 },
//     { day: 27, status: 'unavailable', click: 0 },
//     { day: 28, status: 'unavailable', click: 0 },
//     { day: 29, status: 'available', click: 0 },
//     { day: 30, status: 'available', click: 0 },
//   ],
//   junho: [
//     { day: 1, status: 'available', click: 0 },
//     { day: 2, status: 'available' },
//     { day: 3, status: 'available', click: 0 },
//     { day: 4, status: 'available', click: 0 },
//     { day: 5, status: 'available', click: 0 },
//     { day: 6, status: 'unavailable', click: 0 },
//     { day: 7, status: 'unavailable', click: 0 },
//     { day: 8, status: 'available', click: 0 },
//     { day: 9, status: 'available', click: 11 },
//     { day: 10, status: 'available', click: 0 },
//     { day: 11, status: 'available', click: 0 },
//     { day: 12, status: 'available', click: 0 },
//     { day: 13, status: 'unavailable', click: 0 },
//     { day: 14, status: 'unavailable', click: 0 },
//     { day: 15, status: 'available', click: 0 },
//     { day: 16, status: 'available', click: 0 },
//     { day: 17, status: 'available', click: 0 },
//     { day: 18, status: 'available', click: 0 },
//     { day: 19, status: 'available', click: 0 },
//     { day: 20, status: 'unavailable', click: 0 },
//     { day: 21, status: 'unavailable', click: 0 },
//     { day: 22, status: 'available', click: 0 },
//     { day: 23, status: 'available', click: 0 },
//     { day: 24, status: 'available', click: 0 },
//     { day: 25, status: 'available', click: 0 },
//     { day: 26, status: 'available', click: 0 },
//     { day: 27, status: 'unavailable', click: 0 },
//     { day: 28, status: 'unavailable', click: 0 },
//     { day: 29, status: 'available', click: 0 },
//     { day: 30, status: 'available', click: 0 },
//   ],
//   julho: [
//     { day: 1, status: 'available', click: 0 },
//     { day: 2, status: 'available' },
//     { day: 3, status: 'available', click: 0 },
//     { day: 4, status: 'available', click: 0 },
//     { day: 5, status: 'available', click: 0 },
//     { day: 6, status: 'unavailable', click: 0 },
//     { day: 7, status: 'unavailable', click: 0 },
//     { day: 8, status: 'available', click: 0 },
//     { day: 9, status: 'available', click: 0 },
//     { day: 10, status: 'available', click: 0 },
//     { day: 11, status: 'available', click: 0 },
//     { day: 12, status: 'available', click: 0 },
//     { day: 13, status: 'unavailable', click: 0 },
//     { day: 14, status: 'unavailable', click: 0 },
//     { day: 15, status: 'available', click: 0 },
//     { day: 16, status: 'available', click: 0 },
//     { day: 17, status: 'available', click: 0 },
//     { day: 18, status: 'available', click: 0 },
//     { day: 19, status: 'available', click: 0 },
//     { day: 20, status: 'unavailable', click: 0 },
//     { day: 21, status: 'unavailable', click: 0 },
//     { day: 22, status: 'available', click: 0 },
//     { day: 23, status: 'available', click: 0 },
//     { day: 24, status: 'available', click: 0 },
//     { day: 25, status: 'available', click: 0 },
//     { day: 26, status: 'available', click: 0 },
//     { day: 27, status: 'unavailable', click: 0 },
//     { day: 28, status: 'unavailable', click: 0 },
//     { day: 29, status: 'available', click: 0 },
//     { day: 30, status: 'available', click: 0 },
//   ],
//   agosto: [
//     { day: 1, status: 'available', click: 0 },
//     { day: 2, status: 'available' },
//     { day: 3, status: 'available', click: 0 },
//     { day: 4, status: 'available', click: 0 },
//     { day: 5, status: 'available', click: 0 },
//     { day: 6, status: 'unavailable', click: 0 },
//     { day: 7, status: 'unavailable', click: 0 },
//     { day: 8, status: 'available', click: 0 },
//     { day: 9, status: 'available', click: 0 },
//     { day: 10, status: 'available', click: 0 },
//     { day: 11, status: 'available', click: 0 },
//     { day: 12, status: 'available', click: 0 },
//     { day: 13, status: 'unavailable', click: 0 },
//     { day: 14, status: 'unavailable', click: 0 },
//     { day: 15, status: 'available', click: 0 },
//     { day: 16, status: 'available', click: 0 },
//     { day: 17, status: 'available', click: 0 },
//     { day: 18, status: 'available', click: 0 },
//     { day: 19, status: 'available', click: 0 },
//     { day: 20, status: 'unavailable', click: 0 },
//     { day: 21, status: 'unavailable', click: 0 },
//     { day: 22, status: 'available', click: 0 },
//     { day: 23, status: 'available', click: 0 },
//     { day: 24, status: 'available', click: 0 },
//     { day: 25, status: 'available', click: 0 },
//     { day: 26, status: 'available', click: 0 },
//     { day: 27, status: 'unavailable', click: 0 },
//     { day: 28, status: 'unavailable', click: 0 },
//     { day: 29, status: 'available', click: 0 },
//     { day: 30, status: 'available', click: 0 },
//   ],
//   setembro: [
//     { day: 1, status: 'available' },
//     { day: 2, status: 'unavailable' },
//     { day: 3, status: 'available' },
//     { day: 4, status: 'unavailable' },
//     { day: 5, status: 'available' },
//     { day: 6, status: 'unavailable' },
//     { day: 7, status: 'unavailable' },
//     { day: 8, status: 'available' },
//     { day: 9, status: 'available' },
//     { day: 10, status: 'available' },
//     { day: 11, status: 'available' },
//     { day: 12, status: 'available' },
//     { day: 13, status: 'unavailable' },
//     { day: 14, status: 'unavailable' },
//     { day: 15, status: 'available' },
//     { day: 16, status: 'available' },
//     { day: 17, status: 'unavailable' },
//     { day: 18, status: 'available' },
//     { day: 19, status: 'available' },
//     { day: 20, status: 'unavailable' },
//     { day: 21, status: 'unavailable' },
//     { day: 22, status: 'available' },
//     { day: 23, status: 'available' },
//     { day: 24, status: 'available' },
//     { day: 25, status: 'available' },
//     { day: 26, status: 'available' },
//     { day: 27, status: 'unavailable' },
//     { day: 28, status: 'unavailable' },
//     { day: 29, status: 'available' },
//     { day: 30, status: 'unavailable' },
//   ],
//   outubro: [
//     { day: 1, status: 'available' },
//     { day: 2, status: 'available' },
//     { day: 3, status: 'unavailable' },
//     { day: 4, status: 'available' },
//     { day: 5, status: 'available' },
//     { day: 6, status: 'unavailable' },
//     { day: 7, status: 'unavailable' },
//     { day: 8, status: 'available' },
//     { day: 9, status: 'available' },
//     { day: 10, status: 'available' },
//     { day: 11, status: 'unavailable' },
//     { day: 12, status: 'available' },
//     { day: 13, status: 'unavailable' },
//     { day: 14, status: 'unavailable' },
//     { day: 15, status: 'available' },
//     { day: 16, status: 'available' },
//     { day: 17, status: 'unavailable' },
//     { day: 18, status: 'available' },
//     { day: 19, status: 'available' },
//     { day: 20, status: 'unavailable' },
//     { day: 21, status: 'unavailable' },
//     { day: 22, status: 'available' },
//     { day: 23, status: 'available' },
//     { day: 24, status: 'available' },
//     { day: 25, status: 'unavailable' },
//     { day: 26, status: 'available' },
//     { day: 27, status: 'unavailable' },
//     { day: 28, status: 'unavailable' },
//     { day: 29, status: 'available' },
//     { day: 30, status: 'available' },
//   ],
//   novembro: [
//     { day: 1, status: 'available' },
//     { day: 2, status: 'available' },
//     { day: 3, status: 'unavailable' },
//     { day: 4, status: 'unavailable' },
//     { day: 5, status: 'available' },
//     { day: 6, status: 'unavailable' },
//     { day: 7, status: 'unavailable' },
//     { day: 8, status: 'available' },
//     { day: 9, status: 'available' },
//     { day: 10, status: 'available' },
//     { day: 11, status: 'unavailable' },
//     { day: 12, status: 'unavailable' },
//     { day: 13, status: 'unavailable' },
//     { day: 14, status: 'unavailable' },
//     { day: 15, status: 'available' },
//     { day: 16, status: 'available' },
//     { day: 17, status: 'available' },
//     { day: 18, status: 'available' },
//     { day: 19, status: 'available' },
//     { day: 20, status: 'unavailable' },
//     { day: 21, status: 'unavailable' },
//     { day: 22, status: 'available' },
//     { day: 23, status: 'unavailable' },
//     { day: 24, status: 'available' },
//     { day: 25, status: 'available' },
//     { day: 26, status: 'available' },
//     { day: 27, status: 'unavailable' },
//     { day: 28, status: 'unavailable' },
//     { day: 29, status: 'available' },
//     { day: 30, status: 'available' },
//   ],
//   dezembro: [
//     { day: 1, status: 'available' },
//     { day: 2, status: 'available' },
//     { day: 3, status: 'available' },
//     { day: 4, status: 'unavailable' },
//     { day: 5, status: 'available' },
//     { day: 6, status: 'unavailable' },
//     { day: 7, status: 'unavailable' },
//     { day: 8, status: 'available' },
//     { day: 9, status: 'available' },
//     { day: 10, status: 'available' },
//     { day: 11, status: 'available' },
//     { day: 12, status: 'available' },
//     { day: 13, status: 'unavailable' },
//     { day: 14, status: 'unavailable' },
//     { day: 15, status: 'available' },
//     { day: 16, status: 'available' },
//     { day: 17, status: 'available' },
//     { day: 18, status: 'unavailable' },
//     { day: 19, status: 'available' },
//     { day: 20, status: 'unavailable' },
//     { day: 21, status: 'unavailable' },
//     { day: 22, status: 'available' },
//     { day: 23, status: 'available' },
//     { day: 24, status: 'unavailable' },
//     { day: 25, status: 'available' },
//     { day: 26, status: 'available' },
//     { day: 27, status: 'unavailable' },
//     { day: 28, status: 'unavailable' },
//     { day: 29, status: 'available' },
//     { day: 30, status: 'unavailable' },
//   ],
// };

const useFreeDays = (max = 7, currentMonth = 'junho', allDays = {}) => {
  const freeDays = allDays;

  // remove accents
  const month = currentMonth
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .trim();

  let actual = [];
  if (freeDays[month]) {
    actual = freeDays[month];

    if (max) {
      actual.map((data) => {
        if (data.click >= max) {
          // atingiu o máximo do dia
          Object.assign(data, {
            status: 'unavailable',
          });
        }
      });
    }
  }

  return [actual, freeDays];
};

export default useFreeDays;
